const DOTCMS_DOWN = 'DOTCMS_DOWN';
const DOTCMS_NO_LAYOUT = 'DOTCMS_NO_LAYOUT';
const DOTCMS_NO_AUTH = 'DOTCMS_NO_AUTH';
const DOTCMS_CUSTOM_ERROR = 'DOTCMS_CUSTOM_ERROR';

module.exports = {
    DOTCMS_DOWN,
    DOTCMS_NO_LAYOUT,
    DOTCMS_NO_AUTH,
    DOTCMS_CUSTOM_ERROR,
};
